java/README.md
src/plasma/lib/java/org_ray_spi_impl_PlasmaClientJNI.cc

--------------------------
* jni in java worker adapt the new version of the class ObjectBuffer in arrow
* modify the description of building process in README.md of java worker

Java worker adapt the arrow and fix the problem in README.md

---

java/README.md

- Comparing 2 objects should use `equals`. this example can pass because Java caches small Integer objects, see https://stackoverflow.com/questions/3131136.
- This class doesn't have to be static. Remove it to avoid confusion.
- Also remove trailing spaces.

fix 2 nits in java/README.md

---

src/common/state/ray_config.h
src/ray/common/client_connection.h
src/ray/gcs/redis_context.h
src/ray/id.h
src/ray/object_manager/object_manager.cc
src/ray/object_manager/object_manager.h
src/ray/object_manager/test/object_manager_stress_test.cc
src/ray/object_manager/test/object_manager_test.cc
src/ray/raylet/main.cc
src/ray/raylet/object_manager_integration_test.cc

* Fix some comment mismatches.
* Remove the infinite call in Push function.
N/A

Fix infinite retry

---

.travis.yml
build.sh
java/api/src/main/java/org/ray/api/UniqueID.java
java/example/pom.xml
java/example/run.sh
java/example/src/main/java/org/ray/example/HelloWorld.java
java/pom.xml
java/ray.config.ini
java/runtime-common/src/main/java/org/ray/spi/ObjectStoreProxy.java
java/runtime-dev/src/main/java/org/ray/spi/impl/MockObjectStore.java
java/runtime-native/src/main/java/org/ray/core/impl/RayNativeRuntime.java
java/test.sh
setup_thirdparty.sh
thirdparty/scripts/build_arrow.sh
thirdparty/scripts/setup.sh

The final PR for java worker
1. update the version of Arrow
2. add java test case to ci
3. adaption of the change of Api of plasma java client
4. some adaption work
5. add example module for better usage guide

[WIP]final PR for java worker(Please do not merge, just for code review)

---

src/common/state/ray_config.h
src/ray/object_manager/object_manager.cc
src/ray/object_manager/object_manager.h
src/ray/object_manager/test/object_manager_stress_test.cc
src/ray/object_manager/test/object_manager_test.cc
src/ray/raylet/main.cc
src/ray/raylet/object_manager_integration_test.cc

Add timeout mechanism to Push function instead of retries. (As discussed with @eric-jj @raulchen @elibol)
N/A

Refine the Push failure logic using timeout instead of retries.

---

java/pom.xml
java/runtime-native/src/main/java/org/ray/runner/RunManager.java

Unify the identity of a process while logging so that developers won't get confused.

Unify the identity of a process while logging.

---

python/build-wheel-macos.sh

Pin the setuptools_scm to a specific version to avoid following failure.
```bash
import ray
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ray/__init__.py", line 28, in <module>
import pyarrow  # noqa: F401
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ray/pyarrow_files/pyarrow/__init__.py", line 45, in <module>
__version__ = setuptools_scm.get_version('../', parse=parse_version)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 135, in get_version
parsed_version = _do_parse(config)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 77, in _do_parse
parse_result = …
```

Fix Travis building failure `MAC_WHEELS=1`

---

python/ray/automlboard/README.md

add a monitor implementation for ray tune, named automlboard.

---

python/ray/rllib/env/atari_wrappers.py
python/ray/rllib/examples/serving/cartpole_server.py
python/ray/rllib/utils/actors.py
python/ray/rllib/utils/policy_server.py
test/jenkins_tests/run_multi_node_tests.sh

1. Change training tests to xray for Jenkins tests by passing `RAY_USE_XRAY=1` to Docker environment.
2. `python/ray/rllib/utils/actors.py` directly calls `fetch` which is not supported in raylet.
3. There are many test failures in Jenkins with `WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.`, so I add `dtype` to all spaces.Box.

Change training tests to xray for Jenkins tests

---

java/runtime/src/main/resources/DemoApp.java
java/runtime/src/test/java/org/ray/runtime/functionmanager/FunctionManagerTest.java

Fix function manager test to stage.

Fix function manager test to stage.

---

.github/CODEOWNERS

Disable the codeowner temporarily in alipay/ray.

disable code owners

---

python/ray/cloudpickle/cloudpickle.py
python/ray/ray_constants.py
python/ray/serialization.py
python/ray/tests/test_serialization.py

Secure safe pickle

---

.github/workflows/build-ray-wheel-for-security.yml

1. Every PR or commit onto secure branch will trigger building a wheel for the commit in Github actions.
2. You should go to the page `Github ACtions` to download your wheel. For. example, the built package of the latest commit of this PR is https://github.com/alipay/ray/actions/runs/2344476459
3. We now only support x86 linux ubuntu + py38

Add GitHub actions for secure branch.

---

python/ray/_private/security.py
python/ray/ray_constants.py
python/ray/serialization.py
python/ray/tests/test_security.py
python/ray/tests/test_serialization.py

Unify security config to `RAY_SECURITY_CONFIG_PATH`

[security] Unify security config

---

python/setup.py

We rename package name to secretflow-ray as a special version for supporting secretflow.

Rename package name to secretflow-ray.

---

.github/workflows/BUILD-RAY-WHEELS-ON-MANY-LINUX.yml
python/build-wheel-manylinux2014.sh

In this PR, I removed the wheels for Python3.6 and Python3.7 due to secretflow doesn't need those.

[secretflow-ray]Refine build ray wheels for secretflow.

---

python/ray/__init__.py

Bump to 2.0.0.dev3

---

python/ray/_private/ray_constants.py
python/ray/_private/serialization.py
python/ray/cloudpickle/cloudpickle.py
python/ray/tests/test_serialization.py

Introduce allowed_pickling_list

---

.github/workflows/BUILD-RAY-WHEELS-ON-MANY-LINUX.yml
python/build-wheel-manylinux2014.sh
python/setup.py

Introduce CICD for building wheels.

---

python/setup.py

Update package name to ant-ray

---

python/ray/_private/utils.py

Fix validating normal task allowed list.

---

python/ray/__init__.py
python/setup.py

Sync package version and package name

package version update

---

python/ray/__init__.py

post2 version with minor fix

---

bazel/ray_deps_setup.bzl
thirdparty/patches/redis-quiet.patch
thirdparty/patches/rules_foreign_cc.patch

[Fix][Core] fix redis compile error

---

src/ray/util/array.h

[Fix][Core] Fix compile error about IndexOf

---

src/ray/gcs/gcs_server/gcs_server.ant.cc
src/ray/gcs/gcs_server/gcs_server.cc
src/ray/gcs/gcs_server/gcs_server.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.h
src/ray/protobuf/gcs.proto
src/ray/protobuf/gcs_service.proto
src/ray/rpc/gcs_server/gcs_rpc_server.h

This PR is 1/N implementation of the issue #409 , it just add grpc service and handler for the time being.

[1/N] add virtual cluster grpc service and handler

---

BUILD.bazel
src/ray/common/simple_id.h
src/ray/common/virtual_cluster_id.h
src/ray/gcs/gcs_server/gcs_server.ant.cc
src/ray/gcs/gcs_server/gcs_server.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.h
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc
src/ray/protobuf/gcs.proto
src/ray/protobuf/gcs_service.proto
src/ray/util/util.h

This PR is 6/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) , it just implement CreateOrUpdateVirtualCluster interface.

[6/N][VirtualCluster] Implement CreateOrUpdateVirtualCluster

---

src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.h
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc
src/ray/protobuf/gcs_service.proto

This PR is 9/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) , it just implement `RemoveLogicalCluster` method add refactor the inheritance relationship.

[9/N][VirtualCluster] Implement RemoveLogicalCluster

---

.github/workflows/pypi-nightly.yml
python/setup.py

Add release nightly

---

python/ray/dashboard/modules/job/common.py
python/ray/dashboard/modules/job/job_agent.py
python/ray/dashboard/modules/job/job_head.py
python/ray/dashboard/modules/job/job_manager.py
python/ray/dashboard/modules/job/job_supervisor.py
src/ray/gcs/gcs_server/gcs_actor_manager.cc
src/ray/gcs/gcs_server/gcs_actor_manager.h
src/ray/gcs/gcs_server/gcs_job_manager.cc
src/ray/gcs/gcs_server/gcs_job_manager.h
src/ray/gcs/gcs_server/gcs_server.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc

This PR is 20/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . Fix virtual cluster scheduling for Job Submission.

[20/N][VirtualCluster] Fix virtual cluster scheduling for Job Submission

---

python/ray/_private/state.py
python/ray/dashboard/modules/job/tests/test_job_with_virtual_cluster.py
python/ray/includes/unique_ids.pxd
src/mock/ray/gcs/gcs_client/accessor.h
src/ray/gcs/gcs_client/accessor.cc
src/ray/gcs/gcs_client/global_state_accessor.cc
src/ray/gcs/gcs_client/global_state_accessor.h
src/ray/gcs/gcs_server/gcs_node_manager.cc
src/ray/gcs/gcs_server/gcs_resource_manager.cc

[VirtualCluster] fix code format

---

python/ray/dashboard/modules/job/tests/test_job_with_virtual_cluster.py
src/ray/gcs/gcs_server/gcs_actor_manager.cc
src/ray/gcs/gcs_server/gcs_actor_manager.h
src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
src/ray/gcs/gcs_server/gcs_placement_group_manager.h
src/ray/gcs/gcs_server/gcs_server.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.h

This PR is 24/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . This handle detached job cluster properly

[24/N][VirtualCluster] Handle detached job cluster

---

src/ray/gcs/gcs_client/accessor.ant.cc
src/ray/raylet/node_manager.cc

[VirtualCluster] Fix virtual cluster cleanup

---

python/ray/data/BUILD

https://github.com/antgroup/ant-ray/issues/409

add bazel test target

---

python/ray/dashboard/modules/job/tests/test_job_with_virtual_cluster.py

Enhance stability and reduce execution time of virtual cluster unittest

[VirtualCluster] Enhance stability and reduce execution time of virtual cluster unittest

---

python/ray/dashboard/modules/job/tests/test_job_with_virtual_cluster.py

Improve unittest for better readability and maintainability

[VirtualCluster] Improve unittest for better readability and maintainability

---

.github/workflows/pypi-nightly.yml
.github/workflows/pypi-release.yml

https://github.com/antgroup/ant-ray/issues

Build frontend into whl

---

python/ray/dashboard/state_aggregator.py
python/ray/scripts/scripts.py
python/ray/util/state/common.py
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/protobuf/gcs_service.proto

This PR is a improvement of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . It enriches vcluster list command

[VirtualCluster] enrich vcluster list command

---

.github/workflows/deploy-docs.yaml

Fix deploy-doc

---

.github/workflows/deploy-docs.yaml
doc/source/conf.py

Add document deploy yaml

---

doc/source/conf.py

Fix doc version switcher

---

README.rst
doc/source/conf.py

Ant ray 2.41.0 doc

---

README.rst
doc/source/conf.py

update docment base url

---

.github/workflows/deploy-docs.yaml

update deploy docs yaml

---

ci/ray_ci/utils.py
java/api/pom_template.xml
java/performance_test/pom_template.xml
java/pom.xml
java/runtime/pom_template.xml
java/serve/pom_template.xml
java/test/pom_template.xml
python/ray/_version.py
src/ray/common/constants.h

version change for ant-2.41.0

---

doc/source/ray-overview/installation.rst
doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt

Ready for release

---

README.rst

Update readme for installation

---

.github/workflows/pypi-nightly.yml
.github/workflows/pypi-release.yml

Add macos build option for pypi-release workflow

---

.github/workflows/pypi-nightly.yml
.github/workflows/pypi-release.yml

Fix nightly and release workflow

---

ci/ray_ci/utils.py
java/api/pom_template.xml
java/performance_test/pom_template.xml
java/pom.xml
java/runtime/pom_template.xml
java/serve/pom_template.xml
java/test/pom_template.xml
python/ray/_version.py
python/ray/serve/_private/replica.py
python/ray/serve/batching.py
src/ray/common/constants.h

sync 2.42.0 version change

---

.github/workflows/pypi-nightly.yml
.github/workflows/pypi-release.yml

Fix nightly workflow

---

python/ray/dashboard/client/src/App.tsx
python/ray/dashboard/client/src/components/ResourceUsage.tsx
python/ray/dashboard/client/src/pages/layout/MainNavLayout.tsx
python/ray/dashboard/client/src/pages/virtual_cluster/VirtualClusters.tsx
python/ray/dashboard/client/src/pages/virtual_cluster/hooks/useVirtualClusters.ts
python/ray/dashboard/client/src/service/virtual_cluster.ts
python/ray/dashboard/client/src/type/virtual_cluster.ts
python/ray/dashboard/state_aggregator.py

This PR adds frontend page for the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409)

[VirtualCluster] Add virtual cluster page for dashboard frontend

---

build-docker-ant.sh

Add build docker script for ant ray

---

doc/source/ray-observability/getting-started.rst

Fix virtual cluster doc for compile issue

[VirtualCluster] Fix virtual cluster view doc

---

.github/workflows/ray-ci.yml
build-docker-ant.sh
ci/docker/core.build.ant.Dockerfile
ci/ray_ci/builder.py
ci/ray_ci/linux_container.py
ci/ray_ci/report_gen.py
ci/ray_ci/tester.py
ci/ray_ci/tester_container.py
ci/ray_ci/tests.env.Dockerfile
ci/run/bazel_export_options

[CI] add ray ci in github action

---

python/ray/includes/global_state_accessor.pxi
python/ray/tests/test_state_api.py

[CI] fix failed ci casse

---

python/ray/_raylet.pyx
python/ray/dashboard/client/src/components/ray-visualization/ElementsPanel.tsx
python/ray/dashboard/client/src/components/ray-visualization/InfoCard.css
python/ray/dashboard/client/src/components/ray-visualization/InfoCard.tsx
python/ray/dashboard/client/src/components/ray-visualization/PhysicalVisualization.tsx
python/ray/dashboard/client/src/components/ray-visualization/RayVisualization.css
python/ray/dashboard/client/src/components/ray-visualization/RayVisualization.tsx
python/ray/dashboard/client/src/pages/job/ActorGraph.tsx
python/ray/dashboard/client/src/service/physical-view.ts
python/ray/dashboard/consts.py
python/ray/dashboard/modules/insight/insight_head.py
python/ray/dashboard/modules/reporter/reporter_agent.py
python/ray/util/insight.py

add ray flow insight physical view (#521)

[FlowInsight] add physical view to flow insight

---

doc/source/ray-observability/getting-started.rst

[doc] fix doc error for flow insight

---

python/ray/_raylet.pyx
python/ray/dashboard/client/src/components/ray-visualization/FlameVisualization.tsx
python/ray/dashboard/client/src/components/ray-visualization/InfoCard.tsx
python/ray/dashboard/client/src/components/ray-visualization/PhysicalVisualization.tsx
python/ray/dashboard/client/src/components/ray-visualization/RayVisualization.tsx
python/ray/dashboard/client/src/pages/job/ActorGraph.tsx
python/ray/dashboard/client/src/service/flame-graph.ts
python/ray/dashboard/client/src/service/virtual_cluster.ts
python/ray/dashboard/modules/insight/insight_head.py
python/ray/util/insight.py
python/ray/util/tracing/tracing_helper.py

add flame graph for ray flow insight (#521 )

[FlowInsight] implement flame graph view

---

python/ray/dashboard/client/src/components/ray-visualization/FlameVisualization.tsx
python/ray/util/insight.py

fix ray flow insight flame graph display problem

[FlowInsight] fix flamegraph missing nodes problem

---

python/ray/_raylet.pyx
python/ray/dashboard/client/src/components/ray-visualization/FlameVisualization.tsx
python/ray/dashboard/client/src/components/ray-visualization/InfoCard.tsx
python/ray/dashboard/client/src/components/ray-visualization/PhysicalVisualization.tsx
python/ray/dashboard/client/src/components/ray-visualization/RayVisualization.css
python/ray/dashboard/client/src/components/ray-visualization/RayVisualization.tsx
python/ray/dashboard/client/src/pages/job/ActorGraph.tsx
python/ray/dashboard/client/src/service/flame-graph.ts
python/ray/dashboard/modules/insight/insight_head.py
python/ray/util/insight.py
ray/dashboard/client/src/components/ray-visualization/FlameVisualization.tsx

[FlowInsight] add call stack mode for logical view

---

python/ray/dashboard/client/src/pages/job/ActorGraph.tsx
python/ray/util/insight.py

[FlowInsight] Fix flow insight actor oom

---

python/ray/_raylet.pyx
python/ray/actor.py
python/ray/util/insight.py

fix cuda error on verl and openrhf

[FlowInsight] fix cuda error on verl and openrhf

---

python/ray/_private/worker.py
python/ray/dashboard/client/src/components/ray-visualization/ElementsPanel.css
python/ray/dashboard/client/src/components/ray-visualization/FlameVisualization.tsx
python/ray/dashboard/client/src/components/ray-visualization/InfoCard.tsx
python/ray/dashboard/client/src/components/ray-visualization/PhysicalVisualization.tsx
python/ray/util/insight.py

use http request to replace remote call in flow insight
calling ray.remote when tracking ray.remote may be tricky and buggy

[FlowInsight] use http request to replace remote call in flow insight 

---

python/ray/dashboard/client/src/components/ray-visualization/FlameVisualization.tsx
python/ray/dashboard/client/src/components/ray-visualization/InfoCard.tsx
python/ray/dashboard/client/src/components/ray-visualization/RayVisualization.tsx
python/ray/dashboard/client/src/pages/job/ActorGraph.tsx
python/ray/dashboard/client/src/service/flame-graph.ts
python/ray/util/insight.py

flame graph fix time duration for running tasks

[FlowInsight] flame graph fix time duration for running tasks

---

python/ray/dashboard/client/src/components/ray-visualization/PhysicalVisualization.tsx

add gpu utilization to physical view

[FlowInsight] add gpu utilization to physical view

---

python/ray/util/queue.py

fix queue actor in tracing, see #567 

[FlowInsight] fix queue actor in tracing

---

.github/workflows/pypi-nightly.yml
.github/workflows/pypi-release.yml

[deploy] add py12 release build

---

python/ray/util/insight.py

fix mismatch state in call stack, which is caused by missing count on flow record

[FlowInsight] fix call stack missing count

---

.github/workflows/ray-ci.yml
ci/lint/check-git-clang-format-output.sh
python/ray/_private/services.py
python/ray/runtime_env/runtime_env.py

[CI] add lint check

---

.github/workflows/ray-ci.yml

fix docker max depth exceed issue

[CI] fix ci docker image max depth exceed

---

doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
python/ray/util/debugpy.py
python/requirements_compiled.txt

need to update debugpy dependency to ensure functionality correctness.

[VisualRDB] update debugpy version

---

python/ray/_private/runtime_env/plugin.py
python/ray/tests/conftest.py
python/ray/tests/test_runtime_env_internal_plugins.py
python/ray/tests/test_runtime_env_packaging.py

 [CI] Fix Runtime Env CI

---

.github/workflows/ray-ci.yml

free up ci machine disk space usage

[CI] add clean up docker volumes to free up spaces

---

doc/source/ray-core/handling-dependencies.rst

Add docs for worker in container
#596 

[Doc] Add docs for worker in container

---

.github/workflows/ray-ci.yml
ci/lint/format.sh
python/ray/dashboard/client/src/common/CodeDialogButton/CodeDialogButton.tsx

fix max depth exceeds issue for ray ci

[CI] fix ci max depth exceed

---

doc/source/virtual-cluster/management.rst

Since we support a new interface for removing nodes from a virtual cluster, this PR adds corresponding doc.
#557 #599 

[VirtualCluster][doc] Add doc for removing from a virtual cluster

---

BUILD.bazel
python/ray/autoscaler/_private/monitor.py
python/ray/autoscaler/_private/prom_metrics.py
python/ray/autoscaler/v2/metrics_reporter.py
python/ray/autoscaler/v2/tests/test_metrics_reporter.py
python/ray/dashboard/consts.py
python/ray/dashboard/dashboard_metrics.py
python/ray/dashboard/http_server_head.py
python/ray/dashboard/modules/metrics/metrics_head.py
python/ray/dashboard/modules/reporter/reporter_agent.py
src/ray/common/ray_config_def.h
src/ray/core_worker/core_worker_process.cc
src/ray/gcs/gcs_server/gcs_server.cc
src/ray/gcs/gcs_server/gcs_server_main.cc
src/ray/gcs/gcs_server/gcs_table_storage.h
src/ray/gcs/store_client/observable_store_client.cc
src/ray/gcs/store_client/observable_store_client.h
src/ray/gcs/store_client/redis_store_client.cc
src/ray/raylet/main.cc
src/ray/stats/metric_defs.cc
src/ray/stats/metric_defs.h
src/ray/stats/tag_defs.cc
src/ray/stats/tag_defs.h

[Core] Redis Operations Observing

---

src/mock/ray/gcs/gcs_client/accessor.h

Signed-off-by: BaoMi <ww15897971129@gmail.com>
This PR primarily addresses error0, error5, error6, and error7 in cpp_core_tests. The main modifications were made to the following files:
src/mock/ray/gcs/gcs_client/accessor.h

[CI] Fix cpp_core_tests

---

python/ray/autoscaler/_private/kuberay/autoscaling_config.py

In #548 , we added a new kuberay http client for easier auto-scaling updates (avoiding k8s secrets and rate limiting). This PR uses this client to get autoscaling config.
#545  #548 

[Autoscaler v2] Using kuberay http client to get autoscaling config
