antgroup/ant-ray

src/local_scheduler/local_scheduler.cc

Problem:
* array ```redis_primary_addr``` is in the else block, but are referenced by ```redis_addr``` out of this scope.
Solution:
* since the "if" block won't use ```redis_addr```, inline it.

bugfix: use array redis_primary_addr out of its scope

---

src/common/state/db_client_table.cc

- Problem
During the execution of `cleanup_object_table()` in monitor.py, objects in the dead Plasma manager may be fetched by others. This manager has been marked as "deleted" but the object location tables may have not been cleaned up yet.
This logic would cause: 1) unnecessary fetching attempts; 2) occasionally, if the recovered Plasma manager is in the same machine and takes the same listening port as the dead one, it may connect to itself during fetching and causes unpredictable results.
- Solution
After looking up DB client table, filter the result to drop dead Plasma managers.

do not fetch from dead Plasma Manager

---

src/local_scheduler/format/local_scheduler.fbs
src/local_scheduler/local_scheduler.cc
src/local_scheduler/local_scheduler_client.cc
src/ray/raylet/node_manager.cc

Now, flatbuffer types are defined in `*.fbs` files, such as `src/local_scheduler/format/local_scheduler.fbs`, `src/ray/object_manager/format/object_manager.fbs` and `src/ray/raylet/format/node_manager.fbs`, which will then be turned to `*_generated.h` files. However, the last two files define flatbuffer types in namespace, while the first file doesn't. That caused a problem about variables' name conflicting.
For example, in file `src/ray/raylet/node_manager.cc`, it includes two `*_generated.h` files, and when we need to include another `*_generated.h` file (in fact, we will do it) which also doesn't defines flatbuffer types in namespace, the conflicting problem will appear.
To solve the problem, make sure every `*.fbs` file defines variables in namespace and that's the PR does.

fix redefinition of flatbuffer types

---

java/test/pom.xml

Change surefire version to 2.21.0. In Ant Financial, we use Java 8 which is OK with Surefile 2.20.1. However, for outside users, they may use Java 10. I found there was a strange failure. 
Here is the [discussion](https://github.com/junit-team/junit4/issues/1513) from Junit-Team.
I have tested this change in both Java 8 and Java 10. 
N/A

Change surefire version to 2.21.0 to fix test failure on Java10.

---

src/ray/CMakeLists.txt

Add the dependency gen_local_scheduler_fbs to raylet to mitigate the random building fail (issue 2257). 
Raylet is designed to replace the old ray backend, so gen_local_scheduler_fbs should not be added to rayley dependency. However, currently, raylet is in the way to replace old ray backend.  node_manager.cc has included local_scheduler_generated.h to guarantee the enum consistency. If this dependency is not added, it is not guaranteed that gen_local_scheduler_fbs will build ahead of raylet lib and the building process will fail randomly. 
The final solution is to retire the old ray backed, but now we need to add this dependency.
2257
2185

Mitigate randomly building failure. Issue 2257

---

CMakeLists.txt
src/global_scheduler/CMakeLists.txt
src/local_scheduler/CMakeLists.txt
src/ray/CMakeLists.txt
src/ray/gcs/tables.h
src/ray/raylet/node_manager.cc
thirdparty/scripts/setup.sh

I compared the build log provided by Issue 2257. The setting is `make -j1`. In most cases, we use multi-thread,  so some missing dependencies will not be a problem since other threads may finish building the dependency in time. 
This change fix all the missing dependencies and now we can build ray with `make -j1`.
2257

Fix build failure while using `make -j1`. Issue 2257 

---

python/ray/worker.py

Previously, a worker used shared SerializationContext for different drivers. That caused problems in this case: worker already have callback info for a type kept in shared context (from the former drivers) but the new driver doesn't. Since the worker knows that info so it won't publish again. 
In this change, we make a map (from driver id to SerializationContext) inside worker, so each driver will has its own SerializationContext.
[2165](https://github.com/ray-project/ray/issues/2165)

Use ser context map

---

java/example/src/main/java/org/ray/exercise/Exercise01.java
java/example/src/main/java/org/ray/exercise/Exercise02.java
java/example/src/main/java/org/ray/exercise/Exercise03.java
java/example/src/main/java/org/ray/exercise/Exercise04.java
java/example/src/main/java/org/ray/exercise/Exercise05.java
java/example/src/main/java/org/ray/exercise/Exercise06.java
java/example/src/main/java/org/ray/exercise/Exercise07.java
java/example/src/main/java/org/ray/exercise/Exercise08.java
java/tutorial.rst

Add java worker tutorial
As we already have README.rst for the description of java worker module, build and test, quick start, description of api and sample code for these api, and have example module for sample code, we just reference the tutorial of python https://github.com/ray-project/tutorial,  add exercise code and description, and ensure users could run the exercise with least command in the tutorial.rst.
And this tutorial is generated with the help of @imzhenyu and @raulchen .

java worker tutorial

---

src/ray/gcs/redis_context.cc
src/ray/gcs/redis_context.h
src/ray/gcs/tables.cc

This is a very small change.`subscribe_callback_index_` in `tables.h` is used to represent the callback index in RedisCallbackManager. However, current index only have two values: -1 means not subscribed and 1 means subscribed. There is a mismatch between the meaning and the usage.

Fix subscribe_callback_index_

---

python/ray/__init__.py
python/ray/internal/__init__.py
python/ray/internal/internal_api.py
python/ray/worker.py
src/local_scheduler/lib/python/local_scheduler_extension.cc
src/local_scheduler/local_scheduler_client.cc
src/local_scheduler/local_scheduler_client.h
src/ray/gcs/tables.cc
src/ray/gcs/tables.h
src/ray/object_manager/format/object_manager.fbs
src/ray/object_manager/object_buffer_pool.cc
src/ray/object_manager/object_buffer_pool.h
src/ray/object_manager/object_directory.cc
src/ray/object_manager/object_directory.h
src/ray/object_manager/object_manager.cc
src/ray/object_manager/object_manager.h
src/ray/raylet/format/node_manager.fbs
src/ray/raylet/node_manager.cc
src/ray/raylet/reconstruction_policy_test.cc
test/runtest.py

As discussed with RISE Lab, we will provide some low-level APIs. `ray.internal.free(object_list)` is one of them.
1. Add backend support of `ray.internal.free`.
- Only `ObjectBufferPool` and `ObjectStoreNotificationManager` have the PlasmaClient, I choose `ObjectBufferPool` to do the free operation.
- `ObjectManager` can connect to each other to spread the free request.
- A driver (the python script that calls `ray.internal.free`) will send a request of `FreeObjectsInObjectStore` to `Node Manager`. This `Node Manager` will call free function of its `Object Manager` and the spread flag could be set to true, which means that this `Object Manager` will send the free requests to all the other 
`Object Managers`.
2. Script implementation: add this function to `ray.internal`
3. Add test …

support ray.internal.free

---

python/ray/_private/function_manager.py
python/ray/_private/security.py
python/ray/tests/test_security.py

Support a module level remote function whitelist. You can set the whitelist in a yaml file and set the env var `RAY_SECURERITY_CONFIG_PATH`. A yaml file example :
```
remote_function_whitelist:
- test_security*
```
We will check this whitelist by regular expression.

[security] support remote function whitelist

---

python/ray/scripts/scripts.py

Before this PR, `ray start --head` enables the ray-client-server by default.
After this PR, it's enabled by default:

Disable client-server by default.

---

python/ray/scripts/scripts.py

We now support that the HEAD node is in TEE, and we should prevent other nodes joining to this cluster, as a result, give a random password for head node is a simple approach, with a minor change.

[TEE] Set a random key to avoid other node joining the cluster.

---

src/ray/common/ray_config_def.h

Lineage needs to pin the input objects for the reconstruction,  which increase the memory usage.
The lineage feature is to try to avoid the ObjectLostError and therefore increase the computation stability, however it's still can't fully address the problem but increase the memory usage, so we turn off it by default.

turn off lineage

---

python/ray/autoscaler/_private/monitor.py

Logging the process cmd will print redis password, which may incur safety issues, disable it.

Remove log msg of monitor start cmd for safety reason

---

.bazelrc
python/ray/_private/services.py
python/ray/node.py

The occlum version temporarily close the log monitor, this PR open it.
Besides, the occlum version use `os.posix_spawn` to start new process, however, its file redirection is not as flexible as `subprocess.Popen` such as it only takes positive `int fd` as input but file handler or `subprocess.DEVNULL`( which is "-3"). So this PR makes some conversion.

Enable log to driver

---

python/ray/__init__.py

Releasing ant-ray in pypi encounter naming issue because PEP440 declares that local version names like "occlum" SHOULD NOT be used in public index server. Only [a | b | rc | post] N can be used.
As this "occlum" version is a enhancement of original "1.13.0", this should be a "post" version.

PEP440 qualified package name

---

python/requirements.txt

We use "static" path in aiohttp, however, when `follow_symlinks` is set to true, a path reverse breakdown problem will exist in the static directory file, for example: 
This has been fixed in aiohttp>=3.9.3

Repair `follow_symlinks` bug in old aiohttp version

---

python/ray/_private/ray_constants.py
python/ray/dashboard/modules/job/common.py
python/ray/dashboard/modules/job/job_agent.py
python/ray/dashboard/modules/job/job_manager.py
src/ray/common/constants.h
src/ray/core_worker/core_worker.cc
src/ray/gcs/gcs_server/gcs_job_manager.cc
src/ray/protobuf/gcs.proto
src/ray/raylet/format/node_manager.fbs
src/ray/raylet/node_manager.cc
src/ray/raylet_client/raylet_client.cc
src/ray/raylet_client/raylet_client.h

This PR is 3/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) , it just pass virtual cluster id to gcs when submitting job

[3/N][VirtualCluster] pass virtual cluster id to gcs when submitting job

---

python/ray/dashboard/modules/virtual_cluster/virtual_cluster_head.py
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc
src/ray/protobuf/gcs.proto

This PR provides http APIs at the dashboard.
#417 

[VirtualCluster] Dashboard supports CRUD of virtual clusters [1/N]

---

BUILD.bazel
src/mock/ray/gcs/gcs_client/accessor.h
src/mock/ray/gcs/gcs_client/gcs_client.h
src/ray/common/virtual_cluster_id.h
src/ray/gcs/gcs_client/accessor.ant.cc
src/ray/gcs/gcs_client/accessor.h
src/ray/gcs/gcs_client/gcs_client.cc
src/ray/gcs/gcs_client/gcs_client.h
src/ray/protobuf/gcs_service.proto
src/ray/raylet/node_manager.cc
src/ray/rpc/gcs_server/gcs_rpc_client.h
src/ray/util/logging.h

This PR is 11/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) , it adds `VirtualClusterInfoAccessor`.

[11/N][VirtualCluster] Add VirtualClusterInfoAccessor

---

BUILD.bazel
src/ray/raylet/node_manager.cc
src/ray/raylet/node_manager.h
src/ray/raylet/virtual_cluster_manager.cc
src/ray/raylet/virtual_cluster_manager.h
src/ray/raylet/virtual_cluster_manager_test.cc

This PR is 12/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) , it adds `VirtualClusterManager` at raylet side.

[13/N][VirtualCluster] Add VirtualClusterManager to raylet

---

src/mock/ray/gcs/gcs_client/accessor.h
src/ray/gcs/gcs_client/accessor.ant.cc
src/ray/gcs/gcs_client/accessor.h
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc
src/ray/protobuf/gcs_service.proto

This PR is 14/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) , Raylet only subscribe mixed cluster data.

[14/N][VirtualCluster] Raylet only subscribe mixed cluster data.

---

python/ray/dashboard/modules/job/job_manager.py
python/ray/dashboard/modules/job/tests/test_job_with_virtual_cluster.py
src/ray/common/constants.h
src/ray/common/task/task_util.h
src/ray/raylet/node_manager.cc

This PR is 14/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) , support raylet-based scheduling for actors, normal tasks, and placement groups in virtual clusters, ensuring supervisor actors are scheduled to their respective clusters and drivers run on the correct virtual clusters.

[15/N][VirtualCluster] Complete scheduling for mixed virtual cluster

---

src/ray/common/virtual_cluster_id.h
src/ray/gcs/gcs_server/gcs_init_data.cc
src/ray/gcs/gcs_server/gcs_init_data.h
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc
src/ray/protobuf/gcs.proto

This PR is 13/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) , it adds failover logic.

[16/N][VirtualCluster] Add virtual cluster failover logic

---

src/ray/core_worker/core_worker.cc
src/ray/gcs/gcs_server/gcs_server.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.h
src/ray/protobuf/gcs.proto
src/ray/raylet/format/node_manager.fbs
src/ray/raylet/node_manager.cc
src/ray/raylet_client/raylet_client.cc
src/ray/raylet_client/raylet_client.h

This PR is 18/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) .  Handle job finished event in gcs virtual cluster manager.

[18/N][VirtualCluster] Handle job finished event in gcs virtual cluster manager

---

python/ray/dashboard/modules/job/tests/test_job_with_virtual_cluster.py
python/ray/dashboard/modules/virtual_cluster/tests/test_virtual_cluster.py
python/ray/dashboard/modules/virtual_cluster/virtual_cluster_head.py
src/mock/ray/gcs/gcs_client/accessor.h
src/ray/gcs/gcs_client/accessor.ant.cc
src/ray/gcs/gcs_client/accessor.h
src/ray/gcs/gcs_server/gcs_actor_manager.cc
src/ray/gcs/gcs_server/gcs_job_manager.cc
src/ray/gcs/gcs_server/gcs_server.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc
src/ray/protobuf/gcs.proto
src/ray/protobuf/gcs_service.proto
src/ray/raylet/virtual_cluster_manager.cc
src/ray/raylet/virtual_cluster_manager_test.cc
src/ray/raylet_client/raylet_client.cc

This PR is 21/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . refactor mixed/exclusive cluster to indivisible/divisible cluster.

[21/N][VirtualCluster] refactor mixed/exclusive cluster to indivisible/divisible cluster

---

src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h

…f node instances
This PR is 23/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . This PR adds a node_instances_map to speed up the lookup of node instances.

[23/N][VirtualCluster]add node_instances_map to speed up the lookup of node instances

---

src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc

This PR is 23/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . This PR refactor `LookupNodeInstances`, `ReplenishNodeInstances` and `IsIdleNodeInstance` to `LookupUndividedNodeInstances`, `ReplenishUndividedNodeInstances` and `IsUndividedNodeInstanceIdle` to make them more clear.

[25/N][VirtualCluster] Introduce undevided node instances concept

---

python/ray/dashboard/modules/virtual_cluster/tests/test_virtual_cluster.py
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc
src/ray/protobuf/gcs_service.proto

This PR is 28/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . This PR just fix compile and lint error.

[28/N][VirtualCluster] Fix compile and lint error

---

python/ray/dashboard/modules/job/tests/test_job_with_virtual_cluster.py
src/ray/common/ray_config_def.ant.h
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc

This PR is 27/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . Remove Job Cluster asynchronously

[27/N][VirtualCluster] Remove Job Cluster asynchronously

---

python/ray/dashboard/modules/virtual_cluster/tests/test_virtual_cluster.py
src/ray/common/ray_config_def.ant.h
src/ray/gcs/gcs_client/accessor.ant.cc
src/ray/raylet/node_manager.ant.cc
src/ray/raylet/node_manager.cc
src/ray/raylet/node_manager.h
src/ray/raylet/virtual_cluster_manager.cc
src/ray/raylet/virtual_cluster_manager.h

[VirtualCluster] Delay local node cleanup function

---

python/ray/dashboard/modules/job/cli.py

This PR is 29/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . This pr adds virtual cluster and replica sets options to job submit cli

[29/N][VirtualCluster]Add virtual cluster to job submit cli command

---

src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc

This PR is fix of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . Fix error logs for listeners

[VirtualCluster] Fix error logs for detached actor/pg listeners

---

python/ray/dashboard/modules/virtual_cluster/cli.py
python/ray/scripts/scripts.py

This PR is 30/N implementation of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409), Add create/remove options to cli

[30/N][VirtualCluster] Add create/remove options to cli

---

python/ray/dashboard/modules/job/job_manager.py

This PR is fix of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . This prevents abnormal removal of VirtualCluster instances

[VirtualCluster] Prevent abnormal removal of VirtualCluster instances

---

python/ray/dashboard/state_aggregator.py

This PR is fix of the VirtualCluster (see issue https://github.com/antgroup/ant-ray/issues/409) . Fix cli divided clusters calculation

[VirtualCluster] Fix cli divided clusters calculation

---

.github/workflows/ray-ci.yml

use a long running runner to trigger ecs instead of github's ubuntu runners

[CI] use self-hostd longrun runner

---

python/ray/_private/runtime_env/context.py
python/ray/_private/utils.py
python/ray/tests/test_runtime_env_working_dir.py

When each worker has its own working directory, we need to add the independent working_dir to the LD_LIBRARY_PATH environment variable so that the worker can access and load the required resources.
But we don't contain independent working_dir in LD_LIBRARY_PATH now
#560 

[Core][Runtime Env] Add independent working_dir to LD_LIBRARY_PATH

---

python/ray/_version.py
python/ray/autoscaler/_private/constants.py
python/ray/autoscaler/_private/kuberay/node_provider.py
python/ray/autoscaler/v2/instance_manager/cloud_providers/kuberay/cloud_provider.py

For now, autoscaler depends on KubernetesHttpApiClient to submit scale request to k8s api server. However, k8s api server is generally rate limited while requiring strict authorization. So we need a new http client (`KubeRayHttpApiClient`) which directly talks to kuberay operator.
Please see #545 for detailed REST format.
#545 

[Autoscaler v2] Autoscaler submits scale request to kuberay operator

---

python/ray/dashboard/modules/virtual_cluster/tests/test_virtual_cluster.py
python/ray/dashboard/modules/virtual_cluster/virtual_cluster_head.py
src/ray/common/status.cc
src/ray/common/status.h
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.h
src/ray/protobuf/gcs_service.proto
src/ray/rpc/gcs_server/gcs_rpc_client.h
src/ray/rpc/gcs_server/gcs_rpc_server.h

Sometimes, users or autoscaler need to remove specified nodes from a virtual cluster. This could happen when some nodes have been idle for certain amount of time. This PR provides such an API.

[VirtualCluster] Remove specified nodes from a virtual cluster

---

python/ray/_private/runtime_env/agent/runtime_env_agent.py
python/ray/runtime_env/runtime_env.py
python/ray/tests/test_runtime_env.py
src/ray/common/ray_config_def.ant.h
src/ray/protobuf/runtime_env_agent.proto
src/ray/raylet/local_task_manager.cc
src/ray/raylet/runtime_env_agent_client.cc
src/ray/raylet/runtime_env_agent_client.h
src/ray/raylet/worker_pool.cc
src/ray/raylet/worker_pool.h

Currently, Runtime Env Agent is not aware of the resources of actors and tasks, so it is not possible to limit the use of resources in `worker in container` mode. 
So we add the resource as part of RuntimeEnv to the cache of RuntimeEnv.
We do something as follows
- add serialized `allocated_instances` to runtime env agent proto.
- Change the cache key of all Runtime Env from `serialized_runtime_env` to `runtime_env_key`, `runtime_env_key`, where `runtime_env_key` is defined as `serialized_runtime_env` + `allocated_instances_serialized_json`
- use `worker_resource_limits_enabled` config to control whether allocated resources are serialized, the default value is `False`, the default value of `allocated_instances_serialized_json` is `"{}"`
#563 
method in Tune, I've added it in …

[Core][Runtime Env][9/N] Add allocated resources to Runtime Env Agent

---

python/ray/_private/ray_constants.py
python/ray/_private/runtime_env/agent/runtime_env_agent.py
python/ray/_private/runtime_env/constants.py
python/ray/_private/runtime_env/context.py
python/ray/_private/runtime_env/image_uri.py
python/ray/_private/runtime_env/pip.py
python/ray/_private/runtime_env/virtualenv_utils.py
python/ray/_private/runtime_env/working_dir.py
python/ray/_private/test_utils.py
python/ray/_private/utils.py
python/ray/runtime_env/runtime_env.py
python/ray/tests/conftest.py
python/ray/tests/test_runtime_env_container.py

Ray's current Runtime Env mechanism allows users to specify dependencies (e.g., Python packages, files, or Conda environments) to be provisioned on worker nodes. However, when deploying Ray clusters in containerized environments (e.g., Docker, Kubernetes), users face significant challenges:
- Redundant Dependency Management:
Containers often already include pre-installed dependencies (e.g., system libraries, Python packages). Ray's current Runtime Env forces users to re-specify these dependencies, leading to redundant downloads, installation steps, and increased startup time.
- Inability to Leverage Base Images:
Users cannot directly reference a base container image as the foundation for their Ray workers. This limits the ability to:
- Reuse pre-built environments for consistency and …

[Core][Runtime Env][10/N] Support base worker in container in Runtime Env

---

build-docker-ant.sh

Specify base image for build docker script is broken because --BASE_IMAGE is misspelled

[script] fix image pass arg typo for build docker script

---

python/ray/dashboard/modules/virtual_cluster/tests/test_virtual_cluster.py
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/test/gcs_virtual_cluster_manager_test.cc

Currently, when removing nodes from a virtual cluster, their corresponding replica instances are not correctly returned to the primary cluster. This PR fixes this bug.
#557 

[VirtualCluster] Fix remove nodes from virtual cluster: return to primary cluster

---

doc/source/virtual-cluster/management.rst
python/ray/autoscaler/v2/instance_manager/reconciler.py
python/ray/autoscaler/v2/tests/test_virtual_cluster_autoscaler.py
python/ray/dashboard/modules/virtual_cluster/tests/test_virtual_cluster.py
python/ray/dashboard/modules/virtual_cluster/virtual_cluster_head.py
src/ray/gcs/gcs_server/gcs_virtual_cluster.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster.h
src/ray/gcs/gcs_server/gcs_virtual_cluster_autoscaler_state_manager.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.cc
src/ray/gcs/gcs_server/gcs_virtual_cluster_manager.h
src/ray/protobuf/autoscaler.proto
src/ray/protobuf/gcs.proto
src/ray/protobuf/gcs_service.proto
src/ray/rpc/gcs_server/gcs_rpc_client.h
src/ray/rpc/gcs_server/gcs_rpc_server.h

With this PR, users can set the min/max limits for each node type of a virtual cluster.
#506 

[Autoscaler v2] Virtual cluster supports min/max autoscaling config
